projects:
  ecommerceapi:
    schemaPath: amplify/backend/api/ecommerceapi/build/schema.graphql
    includes:
      - 'N'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
