/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:28be0751-3721-43c0-ac30-72a10241d7e1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_KB3NAVwOd",
    "aws_user_pools_web_client_id": "na8uuppabb7lvf8sjiiqj2u55",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "http://172.23.112.1:20002/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true
};


export default awsmobile;
